import os
os.system('cls')
print("===============================================")
print("Stack Untuk Array")
print("===============================================")
#contoh kasus Stack : Menumpuk baju lipatan kedalam lemari

Baju = []
print("Memasukan Baju Ke dalam Lemari")
Baju.append("Baju Hitam")
print(Baju)
Baju.append("Baju Putih")
print(Baju)
Baju.append("Baju Abu-Abu")
print(Baju)
Baju.append("Baju Hijau")
print(Baju)
Baju.append("Baju Kuning")
print(Baju)
print()
print('Mengeluarkan Baju dari dalam Lemari')
print(Baju)
Baju.pop(-1)
print(Baju)
Baju.pop(-1)
print(Baju)
Baju.pop(-1)
print(Baju)
Baju.pop(-1)
print(Baju)
Baju.pop(-1)
print()
print("===============================================")
print("Stack Untuk Linked List")
print("===============================================")
class Stack:
    def __init__(self):
        self.items = []
    def is_empty(self):
        return len(self.items) == 0
    def push(self, items):
        self.items.append(items)
    def pop(self):
        if self.is_empty():
            raise Exception("Stack is empty")
        return self.items.pop()
s = Stack()
print("Memasukan Baju ke dalam Lemari")
s.push("Baju Hitam")
print(s.items)
s.push("Baju Abu-Abu")
print(s.items)
s.push("Baju Putih")
print(s.items)
s.push("Baju Hijau")
print(s.items)
s.push("Baju Kuning")
print(s.items)
print()
print("Mengeluarkan Baju dari Lemari")
print(s.items)
s.pop()  
print(s.items)
s.pop()  
print(s.items)
s.pop()  
print(s.items)
s.pop()  
print(s.items)
s.pop()  
print(s.items) 
print()
print("===============================================")
print("Queue Untuk Array")
print("===============================================")
Baju = []
Baju.append("Baju Hitam")
print(Baju)
Baju.append("Baju Putih")
print(Baju)
Baju.append("Baju Abu-Abu")
print(Baju)
Baju.append("Baju Hijau")
print(Baju)
Baju.append("Baju Kuning")
print(Baju)
print()
print('Mengeluarkan Baju dari dalam Lemari')
print(Baju)
Baju.pop(0)
print(Baju)
Baju.pop(0)
print(Baju)
Baju.pop(0)
print(Baju)
Baju.pop(0)
print(Baju)
Baju.pop(0)
print()
print("===============================================")
print("Queue Untuk Linked List")
print("===============================================")
class Queue:
    def __init__(self):
        self.items = []
    def is_empty(self):
        return len(self.items) == 0
    def enqueue(self, item):
        self.items.append(item)
    def dequeue(self):
        if self.is_empty():
            raise Exception("Stack is empty")
        return self.items.pop(0)
q = Queue()
q.enqueue("Baju Hitam")
print(q.items)
q.enqueue("Baju Abu-Abu")
print(q.items)
q.enqueue("Baju Putih")
print(q.items)
q.enqueue("Baju Hijau")
print(q.items)
q.enqueue("Baju Kuning")
print(q.items)
print()

print(q.items)
q.dequeue()  
print(q.items)
q.dequeue()  
print(q.items)
q.dequeue()  
print(q.items)
q.dequeue()  
print(q.items)
q.dequeue()  
print(q.items)